# NumPy
- NumPy (or Numpy) is a Linear Algebra Library for Python.
- Numpy has many built-in functions and capabilities.
- Numpy is also incredibly fast, as it has bindings to C libraries.

In [103]:
#Importing numpy as a library
import numpy as np 

# Iteration

##### 1D Array

In [106]:
#Iterate through each element of array and print it
arr1 = np.array([4, 2, 3])
for x in arr1:
  print(x)

4
2
3


##### 2D Array

In [114]:
#Iterate through each element of 2-D array and print array
arr2 = np.array([[1,2,3],[4,5,6]])
for x in arr2:
  print(x)

[1 2 3]
[4 5 6]


In [151]:
#Iterate through each element of 2-D array and print values
for x in arr2:
  for y in x:
    print(y)

1
2
3
4
5
6


##### 3D Array

In [152]:
#Iterate through each element of 3-D array and print values
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# nditer() Function
- It can be used from very basic to very advanced iterations. 

In [118]:
arr5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr5):
  print(x)

1
2
3
4
5
6
7
8


In [119]:
#Access the elements of array as String
arr6 = np.array([1, 2, 3])
for x in np.nditer(arr6, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [120]:
arr7 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr7[:, ::2]):
  print(x)

1
3
5
7


# ndenumerate() Function
- For Enumerated Iteration
- for usecases

##### 1D Array

In [121]:
arr8 = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr8):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


##### 2D Array 

In [123]:
arr9 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr9):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# numpy.sum() Function
- Function on a 2-D array with the axis parameter, it collapses 2D-array to 1-D array! 

##### Numpy sum with axis 0

In [29]:
#Creating Numpy Array
array_2d = np.arange(0, 8).reshape([2,4])
print("2d Array= \n",array_2d) 
#Numpy sum with axis 0
a = np.sum(array_2d, axis = 0)
print("Sum = ",a)

2d Array= 
 [[0 1 2 3]
 [4 5 6 7]]
Sum =  [ 4  6  8 10]


##### Numpy sum with axis 1

In [30]:
print("2d Array= \n",array_2d)
#Numpy Sum With Axis 1
b = np.sum(array_2d, axis = 1)
print("Sum = ",b)

2d Array= 
 [[0 1 2 3]
 [4 5 6 7]]
Sum =  [ 6 22]


# concatenate () function 
- The axis parameter we use for the numpy concatenate () function defines the axis along which we stack the arrays 

##### Concatenate Np arrays with axis 0

In [32]:
#arrays defined
array_1 = np.array([[1,2,3],[1,2,3]])
array_2 = np.array([[4,5,6],[4,5,6]]) 
print("array_1= \n",array_1)
print("array_2= \n",array_2) 
c = np.concatenate([array_1, array_2], axis = 0)
print("Result= \n",c)

array_1= 
 [[1 2 3]
 [1 2 3]]
array_2= 
 [[4 5 6]
 [4 5 6]]
Result= 
 [[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


##### Concatenate Np arrays with axis 1

In [124]:
print("array_1= \n",array_1)
print("array_2= \n",array_2) 
d = np.concatenate([array_1, array_2], axis = 1)
print("Result= \n",d)

array_1= 
 [[1 2 3]
 [1 2 3]]
array_2= 
 [[4 5 6]
 [4 5 6]]
Result= 
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


# vstack() function
- To vertically stack two or more numpy arrays

In [38]:
#initialize arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A= \n",A)
print("B= \n",B)
#vertically stack arrays
voutput = np.vstack((A, B))
print("output = \n",voutput)

A= 
 [[1 2]
 [3 4]]
B= 
 [[5 6]
 [7 8]]
output = 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


# hstack() function
- To horizontally stack two or more numpy arrays

In [39]:
print("A= \n",A)
print("B= \n",B)
#horizintally stack arrays
houtput = np.hstack((A, B))
print("output = \n",houtput)

A= 
 [[1 2]
 [3 4]]
B= 
 [[5 6]
 [7 8]]
output = 
 [[1 2 5 6]
 [3 4 7 8]]


# dstack() Function
- Used to stack along height, which is the same as depth!

In [149]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.dstack((arr_1, arr_2))
print(arr_3)

[[[1 4]
  [2 5]
  [3 6]]]


# Stack() Functions
- Joining 1D-Arrays

##### Stack(), axis 0

In [125]:
C = np.array([1, 2, 3])
D = np.array([4, 5, 6])
arr10 = np.stack((C, D), axis=0)
print(arr10)

[[1 2 3]
 [4 5 6]]


##### Stack(), axis 1

In [126]:
arr11 = np.stack((C, D), axis=1)
print(arr11)

[[1 4]
 [2 5]
 [3 6]]


# hsplit() Function 
- For the horizontal splitting

In [127]:
arr12 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr12, 1)
print(newarr)

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [128]:
arr13 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr13, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# vsplit() Function
- For the vertical splitting

In [129]:
vnewarr = np.vsplit(arr13, 6)
print(vnewarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [130]:
vnewarr = np.vsplit(arr13, 3)
print(vnewarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [131]:
vnewarr = np.vsplit(arr13, 1)
print(vnewarr)

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


# array_split() 
- for splitting arrays, we pass it the array we want to split and the number of splits!

In [150]:
arr_4 = np.array([1, 2, 3, 4, 5, 6])
ar_snewarr = np.array_split(arr_4, 3)
print(ar_snewarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# searchsorted() Function
- It performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
- The searchsorted() method is assumed to be used on the sorted arrays.

In [132]:
# Find the indexes where the value 7 should be inserted
arr14 = np.array([6, 8, 9])
E = np.searchsorted(arr14, 7)
print(E)

1


In [133]:
#Find the indexes where the value 7 should be inserted, starting from the right
arr15 = np.array([6, 7, 8, 9])
F = np.searchsorted(arr15, 7, side='right')
print(F)

2


In [134]:
#To search for more than one value, use an array with the specified values.
arr16 = np.array([1, 3, 5, 7])
G = np.searchsorted(arr16, [2, 4, 6])
print(G)

[1 2 3]


# sort() Function
- The NumPy ndarray object has a function called sort(), that will sort a specified array
Example
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


In [135]:
arr17 = np.array([3, 2, 0, 1])
print(np.sort(arr17))

[0 1 2 3]


In [136]:
#sorting arrays of strings, or any other data type
arr18 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr18))

['apple' 'banana' 'cherry']


In [137]:
#Sorting boolean
arr19 = np.array([True, False, True])
print(np.sort(arr19))

[False  True  True]


##### Sorting 2-D arrays
- Both Arrays are sorted by using sort() function for 2D arrays

In [138]:
arr20 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr20))

[[2 3 4]
 [0 1 5]]


#### NumPy Filtering Arrays

In [141]:
# Create an array from the elements on index 0 and 2
arr21 = np.array([41, 42, 43, 44])
x = arr21[[True, False, True, False]]
print(x)

[41 43]


In [140]:
# Create a filter array that will return only values higher than 42
arr22 = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr22:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr3 = arr22[filter_arr]
print(filter_arr)
print(newarr3)

[False, False, True, True]
[43 44]


In [142]:
#Create a filter array that will return only even elements from the original array
arr23 = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr1 = []
# go through each element in arr
for element in arr23:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr1.append(True)
  else:
    filter_arr1.append(False)
newarr4 = arr23[filter_arr1]
print(filter_arr1)
print(newarr4)

[False, True, False, True, False, True, False]
[2 4 6]


In [143]:
#Creating Filter Directly From Array
arr24 = np.array([41, 42, 43, 44])
filter_arr2 = arr24 > 42
newarr5 = arr24[filter_arr2]
print(filter_arr2)
print(newarr5)

[False False  True  True]
[43 44]


In [144]:
#Create a filter array that will return only even elements from the original array
arr25 = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr3 = arr25 % 2 == 0
newarr6 = arr25[filter_arr3]
print(filter_arr3)
print(newarr6)

[False  True False  True False  True False]
[2 4 6]


# reshape() Function

In [75]:
numpy_ar1 = np.array([1,2,8,9,6,5]) 
# reshaping 1-D array into 2-D
print("1-D reshaped into 2-D\n", numpy_ar1.reshape(2,3)) 
I = np.array([[4,5,6,10],[7,8,9,12]]) 
print("\nReshaped Array with 4 rows and 2 columns\n", I.reshape(4,2)) 

1-D reshaped into 2-D
 [[1 2 8]
 [9 6 5]]

Reshaped Array with 4 rows and 2 columns
 [[ 4  5]
 [ 6 10]
 [ 7  8]
 [ 9 12]]


# np.argmax()
- This function returns the index of the maximum value in the array list

In [146]:
# axis 0
arr26=np.array([[74,23],[56,98]])
print(np.argmax(arr26, axis=0))

[0 1]


In [147]:
# axis 1
print(np.argmax(arr26, axis=1))

[0 1]


# Numpy count() Functions

In [148]:
arr27=np.array([[16,0,56],[2,34,0],[90,87,0]])
print(np.count_nonzero(arr27))
print(np.count_nonzero(arr27,axis=0))

6
[3 2 1]


# EXECRCISE 
## Search the builtin numpy Function to find dot product

### Numpy Dot() function

##### SCALAR NUMPY DOT PRODUCT 

In [97]:
import numpy as np
J = 10
K = 50
print("x= ",J)
print("y= ",K)
ans = np.dot(J,K)
print("ans= ",ans)

x=  10
y=  50
ans=  500


##### Numpy dot product of 1D Arrays

In [98]:
#initialize arrays
L = np.array([3, 1, 7, 4])
M = np.array([2, 4, 5, 8])
print("x= ",L)
print("y= ",M)
#dot product
Ans = np.dot(L, M)
print("Output= ",Ans)

x=  [3 1 7 4]
y=  [2 4 5 8]
Output=  77


##### Dot product over 2D arrays

In [102]:
#initialize arrays
N = np.array([[1, 1], [2, 2]])
O = np.array([[3, 3], [4, 4]])
#dot product
ans_ = np.dot(N, O)
print("Output: \n",ans_)

Output: 
 [[ 7  7]
 [14 14]]


###### Numpy dot product of complex vectors

In [100]:
vec_a = 1 + 2j
vec_b = 1 + 2j
print("x= ",vec_a)
print("y= ",vec_b)
product = np.dot(vec_a, vec_b) 
print("Dot Product  : ", product) 

x=  (1+2j)
y=  (1+2j)
Dot Product  :  (-3+4j)
