# NUMPY
- General-purpose array processing package.
- Numpy provides high-performance multi-dimensional array object, and tools for working with these arrays.
- It is fundamental package for scientific computing with python.

## ARRAY
- A data structure that stores values of the same data-type.In Python this is the main difference between arrays and lists.
+ Python lists contain values corresponding to different data-types, arrays in python can only contain values corresponding to the same data type.

In [3]:
conda install numpy

Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Admin\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.3               |   py38haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                               4.10.1-py38haa95532_1 --> 4.10.3-py38haa95532_0




conda-4.10.3         | 2.9 MB    |            |   0% 
conda-4.10.3         | 2.9 MB    |            |   1% 
conda-4.10.3         | 2.9 MB    | 1          |   1% 
conda-4.10.3         | 2.9 MB    | 1          |   2% 
conda-4.10.3         | 2.9 MB    | 1          |   2% 



CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/conda-4.10.3-py38haa95532_0.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.




In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
#importing numpy
import numpy as np

In [6]:
list1=[1,2,3,4,5]
array1=np.array(list1)
type(array1)

numpy.ndarray

In [7]:
print(array1)

[1 2 3 4 5]


In [8]:
array1

array([1, 2, 3, 4, 5])

In [9]:
array1.shape

(5,)

In [18]:
##multi-dimensional array
list1=[1,2,3,4,4]
list2=[1,2,3,4,4]
list3=[1,2,3,4,4]
array2=np.array([list1,list2,list3])
array2

array([[1, 2, 3, 4, 4],
       [1, 2, 3, 4, 4],
       [1, 2, 3, 4, 4]])

In [20]:
##size of the array
array2.shape

(3, 5)

In [23]:
array2.reshape(5,3)

array([[1, 2, 3],
       [4, 4, 1],
       [2, 3, 4],
       [4, 1, 2],
       [3, 4, 4]])

In [24]:
array2.reshape(1,15)

array([[1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4]])

# INDEXING

In [28]:
##Retrieving or acessing the elements of the array
array3=np.array([1,2,3,4,5,6])

In [29]:
array2[2]

array([1, 2, 3, 4, 4])